### ISSUE TITLE
Any reason for not submitting this upstream?

### ISSUE THREAD

**Issue by fghaas** [Mic92/ansible-lxc#13]
I wonder if there is any real reason for not submitting this to the ansible upstream repo. I've tried this, find it extremely useful, and have written a corresponding inventory script that I'd like to submit upstream. Any thoughts on pushing your connection driver plugin too?

**Comment by Mic92** [comment]
At the time I wrote this plugin, my other rather simple pull requests took very long to get any reponse. That's why initially I have decide to release it as a seperate project. The dependency on python2-lxc could be a problem.

**Comment by fghaas** [comment]
Hmmm, I see a potential license incompatibility (your module is LGPL, Ansible is GPL),~~and a minor issue with `put_file` and `fetch_file` that I can propose a fix for~~ _[Edit: I misread.]_. Other that that you should be fine...

**Comment by Mic92** [comment]
Fixed https://github.com/ansible/ansible/pull/13145

**Comment by fghaas** [comment]
Huh? Any particular reason why you submitted that version? That's nowhere near what's in https://github.com/Mic92/ansible-lxc/blob/master/lxc.py.

Also, the version you submitted doesn't use `container.attach_wait()` at all, which is exactly what's particularly elegant in the version in this repo.

**Comment by Mic92** [comment]
... oh dear. I copied over an old repo of mine

**Comment by Mic92** [comment]
See. Still no upstream response.

**Comment by fghaas** [comment]
I doubt upstream reviews any code that is failing in the build CI environment. As far as I interpret https://travis-ci.org/ansible/ansible/builds/91253710, it's failing on Python 3.4 and 3.5.

I think you need `except select.error as e` there, no?

**Comment by Mic92** [comment]
Then it would fail for py24, which they also support until the redhat release expires.
**Update** they excluded this check for python2.4

**Comment by Mic92** [comment]
Also the failure is not in my code, but in already existing.
