### ISSUE TITLE
Missing precise use case in Readme

### ISSUE THREAD

**Issue by thibault** [Mic92/ansible-lxc#14]
I'm looking for a way to use Ansible to run tasks on lxc containers _on a remote server_. I usually use ssh to access the remote host, and lxc-attach to the containers. I don't want to run a sshd on each container.

Now, since I'm very new to Ansible, I'm having a hard time understanding if your plugin fits that need, or if it's only dedicated to work on local vm's?

I think it would be helpful if your "usage" section was a little more detailed to add more precise use cases.

Thank you for your work.

**Comment by Mic92** [comment]
This plugin cannot be used in the way you want. It access local lxc container from the server using liblxc. You have basically 2 options:
1. Have a sshd installed in every container and use conventional way.
2. Use ansible or your own script to start ansible locally and deploy your container using the plugin.

LXD has remote api, so this would be possible, but this is a different story.

**Comment by thibault** [comment]
@Mic92 Ok, I understand better now. Thank you for taking the time to answer.
