### ISSUE TITLE
Has ansible-lxc been tested with unprivileged containers?

### ISSUE THREAD

**Issue by joaocc** [Mic92/ansible-lxc#3]
Hi @Mic92,
Have you tested this with unprivileged containers (https://help.ubuntu.com/lts/serverguide/lxc.html#lxc-unpriv)? 
Thx

**Comment by Mic92** [comment]
Not yet. But it should not make any difference, as unprivileged containers also use lxc-attach. If you install containers in $HOME/.lxc, you have to run ansible with the same user of course. Just open an issue in case of problems.

**Comment by joaocc** [comment]
I haven't started using them. Still evaluating what is the impact in things like auto-start, ip assignment and compatibility with overlayfs and/or btrfs (seems to only support ZFS and BTRFS).

If/when we decide to use it, I will try to integrate with ansible-lxc and will let you know.
