### ISSUE TITLE
need to run ansible as sudo to use lxc connection

### ISSUE THREAD

**Issue by joaocc** [Mic92/ansible-lxc#8]
Hi,
I am trying to connect with ansible to lxc-guests in the control machine.

The playbook is as simple as:

```
- name: gather facts from guests...
  sudo: true
  hosts: all-my-guests
  gather_facts: yes
  roles:
    - { role: debug-dump-all }
```

This playbook runs perfectly both with remote guests (via SSH) or lxc-guests also via SSH.
It also runs ok when I run "ansible-playbook" via sudo.

```
sudo bash run--ansible.sh provision--guests.yml
```

(in this case, I am calling a script that calls "ansible-playbook")
However, if I do...

```
    bash run--ansible.sh provision--guests.yml
```

... then I get the following errors:

```
TASK: [debug-dump-all | Dump All Vars] **************************************** 
Process SyncManager-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 250, in _bootstrap
    sys.stdin = open(os.devnull)
IOError: [Errno 13] Permission denied: '/dev/null'
Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 324, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/bin/ansible-playbook", line 264, in main
    pb.run()
  File "/usr/lib/pymodules/python2.7/ansible/playbook/__init__.py", line 348, in run
    if not self._run_play(play):
  File "/usr/lib/pymodules/python2.7/ansible/playbook/__init__.py", line 789, in _run_play
    if not self._run_task(play, task, False):
  File "/usr/lib/pymodules/python2.7/ansible/playbook/__init__.py", line 497, in _run_task
    results = self._run_task_internal(task, include_failed=include_failed)
  File "/usr/lib/pymodules/python2.7/ansible/playbook/__init__.py", line 439, in _run_task_internal
    results = runner.run()
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 1485, in run
    results = self._parallel_exec(hosts)
  File "/usr/lib/pymodules/python2.7/ansible/runner/__init__.py", line 1369, in _parallel_exec
    manager = multiprocessing.Manager()
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 99, in Manager
    m.start()
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 528, in start
    self._address = reader.recv()
EOFError
```

Any idea?
Is this supposed to work only in sudo on the command line (even if I have sudo in the tasks themselves)?
Can I workaround this by adding the user under which ansible runs on the control machine to some group?

Thanks

**Comment by Mic92** [comment]
So it looks to me from the stacktrace that ansible fails on the host not inside lxc. Can you add the following to your bash script:

```
ls -la /dev/null
```

or maybe run instead of ansible-playbook:

```
strace -f -o /tmp/ansible.trace ansible-playbook
```

and give me the content of this file

**Comment by joaocc** [comment]
Ok.You are correct. Yesterday evening I corrected a bug somewhere else that was causing /dev/null to have bad permissions.
Unfortunately, I now have another error (_unsupported connection type: lxc_), but I will check if it is some basic ansible install issue before bothering you :)
Thanks

**Comment by joaocc** [comment]
After correcting that bug, I still cannot access lxc guests unless i run via "sudo ansible-playbook ... -vvvv".
For reference, this is with lxc 1.0.7.

```
- name: gather facts from guests... all... before... @14 (update facts.d)
  sudo: true
  gather_facts: yes
  hosts: hsz-is-guest
  roles:
    - { role: debug-dump-all, hsz__dumpall__id: x140 }
```

(no sudo)

```
2015-07-22 00:32:23,845 p=11058 u=vagrant |  GATHERING FACTS *************************************************************** 
2015-07-22 00:32:23,904 p=11058 u=vagrant |  fatal: [h-lemp-1] => h-lemp-1 is not running
```

(with sudo)

```
GATHERING FACTS *************************************************************** 
<h-lemp-1> THIS IS A LOCAL LXC DIR
<h-lemp-1> REMOTE_MODULE setup
<h-lemp-1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1437525344.97-178625072845690 && echo $HOME/.ansible/tmp/ansible-tmp-1437525344.97-178625072845690']
<h-lemp-1> PUT /tmp/tmputpsBO TO /home/vagrant/.ansible/tmp/ansible-tmp-1437525344.97-178625072845690/setup
<h-lemp-1> EXEC ['/bin/sh', '-c', u'LANG=C LC_CTYPE=C /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1437525344.97-178625072845690/setup; rm -rf /home/vagrant/.ansible/tmp/ansible-tmp-1437525344.97-178625072845690/ >/dev/null 2>&1']
ok: [h-lemp-1]
```

Thx

**Comment by Mic92** [comment]
Sorry, I should have read your bug report more properly. The user executing this playbook needs to have access to the containers, which is usually not the case for unprivileged users. You can verify access that by using `lxc-ls`, which should return the container you want to access. An alternative would be to use of unprivileged lxc containers.

**Comment by joaocc** [comment]
Your initial response was excellent, and pointed to the problem with the original error.
Also, your explanation for the underlying issue that only surfaced in my latest report makes sense. I have to check if I can add the vagrant account to some member that has privileges to use lxc-\* commands.
I think we can close this. Thx!
